sudo: false
language: go
go:
- 1.11.x
env:
  global:
    - GOARCH=amd64
install:
- go get github.com/alecthomas/gometalinter
- gometalinter --install --update
before_script:
- gometalinter --disable-all --vendor --enable=vet --enable=gofmt --enable=golint --enable=ineffassign --enable=misspell --enable=deadcode ./...
script: 
- go test ./...
notifications:
  email: false
