sudo: false
language: go
go:
- 1.12.x
env:
  global:
    - GOARCH=amd64
install:
- GO111MODULE=off go get -u github.com/golangci/golangci-lint/cmd/golangci-lint                                       
before_script:
- golangci-lint run --no-config --disable-all --enable=vet --enable=gofmt --enable=gocyclo --enable=golint --enable=ineffassign --enable=misspell --enable=deadcode --tests=false ./...                                                     
script: 
- GO111MODULE=on go test -mod=vendor ./... -p 1
notifications:
  email: false
