syslog:
  server: ldaps.example.com
  port: 514
  enable: true #defaults to false if not specified

user:
  - name: Administrator
    password: changeme
    role: admin
    enable: true
  - name: foobar
    password: changeme
    role: user
    enable: false

ldap:
  server: ldaps.example.com
  port: 636
  enable: true
  baseDn: ou=People,dc=example,dc=com
  userAttribute: uid
  groupAttribute: memberUid
  searchFilter: objectClass=posixAccount

ldapGroup:
  - role: admin
    group: cn=<%= vendor %>,cn=bmcAdmins
    groupBaseDn: ou=Group,dc=example,dc=com #the baseDn to lookup group in.
    enable: true
  - role: user
    group: cn=<%= vendor%>,cn=bmcUsers #the group in ldap
    groupBaseDn: ou=Group,dc=example,dc=com #the baseDn to lookup group in.
    enable: false
  - role: user
    group: RemoveGroup
    enable: false

ntp:
   enable: true
   server1: ntp0.example.com
   server2: ntp1.example.com
   server3: ntp3.example.com
   timezone: CET

network:
  sshEnable: true
  dnsFromDhcp: true  #bmc to get its DNS address from dhcp
  ipmiEnable: true
  dhcpEnable: true
  solEnable: true #serial over lan
  sshPort: 22
  ipmiPort: 623

#an example of setting the license key based on vendor.
<%= if ( vendor == "hp" ) { %>
license:
  key: ASDFKLAMDNARALKNBA123
<% } %>
